### ISSUE TITLE
Wrong padding multiplier/wrong number of users for 2020-08-22?

### ISSUE THREAD

**Issue by daimpi** [janpf/ctt#4]
On the 22nd August something weird is happening again:

@micb25's [graph](https://micb25.github.io/dka/#positiv-getestete-personen-die-diagnoseschl%C3%BCssel-teilten-gesch%C3%A4tzt) is showing 86 users, while your graph is showing 66 and the output of @mh-'s parser [shows](https://ctt.pfstr.de/users/2020-08-22.txt) "70 users" with some unparsed keys and a warning regarding the multiplier. This might be related to https://github.com/corona-warn-app/cwa-server/issues/723, not sure tbh 🤷.

**Comment by janpf** [comment]
Thanks for notifying me!

> the output of @mh-'s parser "70 users" with a warning regarding the multiplier

this is happening, because 3393 keys are not divisible by 5, but I'm forcing it to use a multiplier of 5 anyways, because that's the multiplier that is used at the moment. Hence the warning. Something seems to be broken with this package.

> your graph is showing 66 and the output of @mh-'s parser "70 users" with some unparsed keys

yes, they will [Edit: sometimes not] show exactly identical numbers, as the files are generated on the "daily packages", while the graphs are calculated based on the "hourly packages".

There are 20 keys (4 without the padding!) unparsed according to the file, so those unparsed keys shouldn't make much difference

>This might be related to [corona-warn-app/cwa-server#723](https://github.com/corona-warn-app/cwa-server/issues/723)

This seems very likely, since I calculate the number of users by [counting the numbers of 6s](https://github.com/mh-/diagnosis-keys/blob/master/doc/algorithm.md#counting-users).


Given the fact that on that day in the hourly packages there are 66 6s and @mh-'s parser shows 70 users for the daily package, the 66 users should atleast be good lower bound, if not even a pretty good approximation of the number of users.

Of course I'm open to suggestions for more accurate calculations, although I don't know how to improve it at the moment.

**Comment by daimpi** [comment]
I see, makes sense 🙂 

>yes, they will almost never show exactly identical numbers, as the files are generated on the "daily packages", while the graphs are calculated based on the "hourly packages".

Interesting. I'd have thought that those should come out identical unless there is some problem (like in this case)… I checked [a](https://ctt.pfstr.de/users/2020-08-15.txt) [few](https://ctt.pfstr.de/users/2020-08-16.txt) ["normal"](https://ctt.pfstr.de/users/2020-08-14.txt) [packages](https://ctt.pfstr.de/users/2020-08-17.txt) and the user number there actually seems to match the numbers shown in your graph (and also @micb25's for that matter).

**Comment by janpf** [comment]
> actually seems to match the numbers shown in your graph

yes, you're right, I felt it happened way more often, than it actually does.
Recently they seem to match more often than [not](https://ctt.pfstr.de/users/2020-08-18.txt) and if [not](https://ctt.pfstr.de/users/2020-08-04.txt) they are only off by one or two keys.

**Comment by daimpi** [comment]
> yes, you're right, I felt it happened way more often, than it actually does.

Ah interesting… maybe your past experience was influenced by [the bug](https://github.com/corona-warn-app/cwa-server/issues/650#issuecomment-656209111) in the retention and shifting policy which since has been fixed?

**Comment by janpf** [comment]
possibly, because when I noticed I stopped updating and redownloading older packages: 70be049
